### PR TITLE
Implement protocol relativity

### PR DESCRIPTION
**Pull request by jieter**
#123 a little bit more concise...

Will push the test-https-support file in a minute.

### CODE REVIEW

**Comment by jieter** [comment]
Any thoughts? @ximex @calvinmetcalf @brunob

**Comment by ximex** [comment]
If i check the OpenWeatherMap for https support, the http variant doesn't work too. Any Idea? Are there some layers obsolete?

**Comment by jieter** [comment]
hmm, It looked like that to me, but the tiles load very slow and have bad contrast with the grey map background...

**Comment by ximex** [comment]
ok i see. it took about 30-40sec to load...
the implementation looks fine to me

**Comment by jieter** [comment]
thanks @ximex, for working on this.

**Pull request merged**
