### PR TITLE
Add Carto "Voyager" tiles

### PR DESCRIPTION
**Pull request by zerocrates**
The newer Voyager tiles are available under the same terms as Positron and Dark Matter, confirmed by https://github.com/CartoDB/basemap-styles#1-web-raster-basemaps

### CODE REVIEW

**Comment by jieter** [comment]
Looks good, thanks!

**Comment by jieter** [comment]
Yes:
> Limitations: free usage for up to 75,000 mapviews per month, none-commercial services only. For bigger usage and other cases contact CARTO sales for enterprise service key.

**Comment by tmh12345** [comment]
@jieter 
Do you have any idea about map tiles without limitation. Currently I am using osm standard tile. But it country name is follow the country languae, but what i wan is english.

**Comment by jieter** [comment]
Have a look at the list here:

http://leaflet-extras.github.io/leaflet-providers/preview/

I have no listing of limits. Also: limitless is a lot to ask from a free provider...

**Comment by tmh12345** [comment]
@jieter 
Noted and thank q.

**Pull request merged**
