### PR TITLE
Update NASAGIBS.ModisTerraSnowCover tiles url

### LINKED ISSUE #389: NASAGIBS.ModisTerraSnowCover probably broken
I wasn't able to make `NASAGIBS.ModisTerraSnowCover` work in any context so I am not sure if it is still available. I have not found any information on GIBS about that so I am flagging it out as a potentially broken source. It doesn't work in preview and I wasn't able to fetch its tiles directly in the same way as other NASAGIBS sources  (error 400).

### PR DESCRIPTION
**Pull request by brunob**
fixes: #389

### CODE REVIEW

**Comment by brunob** [comment]
@jieter any thoughts ?

**Comment by jieter** [comment]
Not sure why running the tests results in a timeout, but #392 and #393  complete without problems, so probably something not related to this change?

**Comment by brunob** [comment]
> Not sure why running the tests results in a timeout, but #392 and #393 complete without problems, so probably something not related to this change?

Maybe the last commit make the test fail, anyway i think we can merge this small change.

**Comment by jieter** [comment]
Updated with latest master, all green. I'll merge.

**Pull request merged**
