### PR TITLE
Introduce HEREv3 (using apiKey instead of app_id and app_code)

### LINKED ISSUE #342: Use HERE apiKey v3 instead of legacy app_id and app_code
I cannot generate an `app_id` / `app_code` pair in my (freshly generated) HERE account any more, they seem to have switched to a single apiKey authorization. 
https://developer.here.com/documentation/map-tile/dev_guide/topics/quick-start-map-tile.html

I would gladly craft a PR to fix this, but I am not sure, if `*.maps.api.here.com` with `app_id` and `app_code` is still functional. Does anyone have more intel on this?

### PR DESCRIPTION
**Pull request by mcguffin**
Use Tile API-URL and apiKey as described in latest HERE docs: https://developer.here.com/documentation/map-tile/dev_guide/topics/quick-start-map-tile.html
Will fix #342

### CODE REVIEW

**Comment by brunob** [comment]
@jieter any thoughts ?

**Comment by jieter** [comment]
Yes, the readme links to the preview, using `[Available HEREv3 layers](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=HEREv3)`, but 'HERE' is completely ignored from preview:
https://github.com/leaflet-extras/leaflet-providers/blob/52bfb509ab608ff0ad524d6812384883df9f03ed/preview/preview.js#L81

The reason being that we kept exceeding the free plan, even with a single layer in the preview list.

I'd say there is limited value in adding these providers we cannot reliably show previews for, as they are not really discoverable.

**Comment by brunob** [comment]
@jieter nice catch maybe it could be better if @mcguffin remove the mention & link to preview for HERE in the readme ?

**Comment by brunob** [comment]
LGTM

**Comment by jieter** [comment]
Merged, thanks @mcguffin

**Comment by stell** [comment]
Can someone tag 1.9.2 with this update? Thanks!

**Comment by brunob** [comment]
@stell no hurry, we were waiting to merge others PR, now that it's done, we will shortly publish a new tag when our free time will allow it :)

**Pull request merged**
