### PR TITLE
Add apikey parameter to thunderforest URLs

### PR DESCRIPTION
**Pull request by tomhughes**
http://www.thunderforest.com/blog/apikeys-now-available/

### CODE REVIEW

**Comment by jieter** [comment]
Thanks for the PR, but it [makes the tests fail](https://travis-ci.org/leaflet-extras/leaflet-providers/builds/158471158). It will need an example API code in [this map](https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/shared.js#L4)

**Comment by tomhughes** [comment]
So what's the best way of handling that? Somebody will need to signup for a key at the free level so we can put that in - how was that handled for the other providers?

**Comment by jieter** [comment]
Yes, I signed up for the HERE code, I think MapBox provided the MapBox code. If you are willing to signup for a free code, we can just replace it if needed later. Contacting thunderforest might also be an option.

**Comment by tomhughes** [comment]
Right, I already have an account but I should be able to create another one under an alias. I suspect if I ask @gravitystorm he would just have to create an account in his systems to provide a key anyway.

**Comment by tomhughes** [comment]
I've added an API key but unfortunately the test failed for completely different reasons because it couldn't download phantomjs...

**Comment by jieter** [comment]
I gave the CI a restart, all green now!

**Pull request merged**
