### PR TITLE
update devDependencies

### PR DESCRIPTION
**Pull request by ximex**

### CODE REVIEW

**Comment by jieter** [comment]
I will update when we need newer versions.

**Comment by ximex** [comment]
what is bad that you won't update yet?

**Comment by jieter** [comment]
Nothing bad. I just want to check what's changed and verify all still works. Since there is no reason for that, I'll rather stay on the current versions.

If you can provide reasons to update, we'll might reconsider.

**Comment by ximex** [comment]
ok.
i have checked the uglify-js command.
i can't check the test command local (see other bug report)
i didn't check the mversion command but i read the changelogs and looked in the docs if the syntax has changed.

**Pull request closed without merging**
