### PR TITLE
added Stadia Maps to list of providers

### PR DESCRIPTION
**Pull request by holtalanm**
https://stadiamaps.com/

ToS: https://docs.stadiamaps.com/#legal-stuff

Implementation from their documentation regarding Leaflet: https://docs.stadiamaps.com/raster/#displaying-a-map-leaflet

### CODE REVIEW

**Comment by brunob** [comment]
@jieter any thoughts ?

**Comment by jieter** [comment]
LGTM

**Comment by brunob** [comment]
Thx @holtalanm :)

**Comment by jieter** [comment]
Hmm, there is no preview API key configured, so http://leaflet-extras.github.io/leaflet-providers/preview/#filter=Stadia shows grey maps.

We should either keep it out of the preview, or add an example API code:
https://github.com/leaflet-extras/leaflet-providers/blob/86278408c9896e6883ffa0d6217ea3b5d63d8b92/preview/shared.js#L4-L12

**Comment by brunob** [comment]
As what i can read in their doc you don't need an API key to use the tiles, but the error is `403 Forbidden Request forbidden by administrative rules. `, and i've seen this one while testing their static map API ref https://seenthis.net/messages/822843#message822884

So, there might be a temporary bug from their side ?

**Comment by holtalanm** [comment]
while their api has a free tier, users still need to have an account, and have their domain whitelisted within that account.  This is explained in their leaflet documentation, as well:

```
everything should work seamlessly as long as you have an active plan for your domain
```

Not sure where that should be communicated within the leaflet-providers codebase, though.

**Comment by brunob** [comment]
@holtalanm so you should add this mention in the readme, and we should from our part don't list these tiles in the demo page.

**Comment by lseelenbinder** [comment]
Hi @holtalanm, @brunob, we (I'm co-founder of @stadiamaps) just added a property on our side allowing the preview domain (leaflet-extras.github.io). Are there any other domains we should add so there's not a weird grey space where our maps should be? 😄

**Comment by jieter** [comment]
@lseelenbinder leaflet-extras.github.io should be enough, thanks!

**Pull request merged**
