### PR TITLE
Ref #251 : Handle retina for Stamen & CartoDB tiles

### PR DESCRIPTION
**Pull request by brunob**
Following #251 and comments.

### CODE REVIEW

**Comment by jieter** [comment]
What about [our custom retina detection](https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js#L59-L69), does that still make sense?

**Comment by brunob** [comment]
Nice catch @jieter i've forgotten this option, i'm not even sure that `{r}` option is enough since `detectRetina` is set to `false` by default http://leafletjs.com/reference-1.2.0.html#tilelayer-detectretina

I have no retina device to test it, we should ask test on all of this before going further.

**Comment by zerocrates** [comment]
`{r}` in a provider URL works fine with current leaflet on a Retina device. `detectRetina` is really "fake Retina": it adjusts the zoom and renders twice as many tiles: you get the sharpness but everything is small. It's actually counterproductive to use it when you have "real" Retina tiles available.

I'm not sure whether the "custom" Retina support in leaflet-providers really makes sense anymore... from my reading it only is useful for tilesets that _have_ retina support but just don't use the `@2x` string.

**Comment by zerocrates** [comment]
Further, `{r}` is _already_ being used in a provider, Wikimedia, so it seems that's already been determined to not be an issue.

**Comment by jieter** [comment]
I agree, the custom leaflet-providers fake retina should be removed.

**Pull request closed without merging**
