### PR TITLE
add hikebike-hillshading

### PR DESCRIPTION
**Pull request by ximex**
hope this PR has no errors

### CODE REVIEW

**Comment by jieter** [comment]
thanks for fixing!

**Comment by jieter** [comment]
released v1.0.28

**Comment by jieter** [comment]
hmm, something is not quite right since these two use the same layer:

http://leaflet-extras.github.io/leaflet-providers/preview/#filter=HikeBike

Fixed in 77bc62cd8b6c183bcf8175ed56fef1670b6b64d3 and released 1.0.29

**Comment by ximex** [comment]
damn... but good idea with this test case

**Pull request merged**
