### PR TITLE
add npm install instructions

### PR DESCRIPTION
**Pull request by vincerubinetti**

### CODE REVIEW

**Comment by brunob** [comment]
Doc is always welcome, but i doubt on this, any thoughts @jieter ?

**Comment by jieter** [comment]
I'd say a single package manager should be enough, I think yarn users know that they can replace `npm` with `yarn`. Can we also use unpkg for `leaflet-providers.js`, avoiding the need to download it? That would be a nice improvement.

**Comment by brunob** [comment]
> Can we also use unpkg for leaflet-providers.js, avoiding the need to download it? That would be a nice improvement.

Nice catch `https://unpkg.com/browse/leaflet-providers@latest/leaflet-providers.js` does the job ping @vincerubinetti

**Comment by vincerubinetti** [comment]
I've updated the branch. That unpkg link was incorrect, I fixed it. The yarn command is just there for copy/paste convenience but I removed it.

**Review by brunob — APPROVED** [review]

**Comment by jieter** [comment]
Looks good, thanks!

**Pull request merged**
