### PR TITLE
Update MapBox API to v4

### LINKED ISSUE #150: Can't seem to get it working
Hello,

I'm trying to use MapBox with Leaflet JS using your this project.

Here is my code:

````js
var map = L.map('map').setView(
    [latitude, longitude],
    13
);

L.tileLayer.provider('MapBox.jamesking56.ligeph22').addTo(map);
L.geoJson(geoJson, {}).addTo(map);
````

What am I doing wrong? There's no console errors but I just get a blank grey map with my GeoJSON on it (no tiles)

### PR DESCRIPTION
**Pull request by gutenye**
USAGE:

```
 L.tileLayer.provider('MapBox',{id: 'ID', accessToken: 'ACCESS_TOKEN'}).addTo(map)'
```

and fix #150

### CODE REVIEW

**Comment by jieter** [comment]
Thanks.

Can you also update the documentation in README.md?

**Comment by gutenye** [comment]
That access_token is not mine, I get it from the official documentation https://www.mapbox.com/developers/api/maps/#tiles

**Comment by jieter** [comment]
Should be OK then.

**Comment by jieter** [comment]
Looking good, thanks.

**Comment by jieter** [comment]
released 1.1.1

**Pull request merged**
