### PR TITLE
Remove HERE layers

### PR DESCRIPTION
**Pull request by jieter**
Since the free tier is only valid for 90 days, they're not really free any more: https://developer.here.com/plans/api/consumer-mapping

Should we remove HERE completely?

refs #194, #205

### CODE REVIEW

**Comment by jieter** [comment]
@brunob Any thoughts?

Just forced-pushed rebased branch...

**Comment by brunob** [comment]
Maybe some people would like to use on a paid plan, but i think we should remove it. If it become a big deal, we could revert the change.

**Comment by brunob** [comment]
@jieter i've just seen #205 which mention that Here tiles have been shut down...

**Comment by jieter** [comment]
Yeah, saw that too, but it seems not entirely correct as they still seem to offer the 90-day trial.

**Comment by jieter** [comment]
@brunob good to merge?

**Comment by brunob** [comment]
Sure :)

**Comment by jieter** [comment]
Released v1.1.8

**Comment by roxeteer** [comment]
They still have a free basic plan with "100,000 transactions per month" but that requires setting up an account.

Is your plan that `leaflet-providers` is restricted to have only providers that you can use without API keys?

**Comment by jieter** [comment]
@roxeteer Only valid for 90 days.

2016-03-23-100301_183x235_scrot

No problem if API keys are required, but the 90 day limit makes it not really free to me.

**Comment by roxeteer** [comment]
image

**Comment by jieter** [comment]
totally missed that.

Anyway, I think we were exceeding those 100k tiles somehow, because my plan got cancelled.

So I guess we can revert this PR, but we do need to find a way to limit the number of tiles used in the preview.

**Comment by roxeteer** [comment]
I missed it first, too. It's hardly a surprise that companies want to hide their free tiers :D

**Comment by brunob** [comment]
@jieter we could revert the PR and just remove HERE form preview page.

**Comment by brunob** [comment]
Ha sorry, i've missed #209 ;)

**Comment by jieter** [comment]
For reference, I recently had some email contact with a guy from HERE, because the example account I created was exceeding the limits again. I explained the usage of the account and the idea of the project, this was his response:

> Thank you for your reply and explanation.
>
> We do appreciate the fact that you are including HERE on your website.
> 
> For now I would say it is ok to continue as is. I will monitor the usage and contact you if needed.

**Comment by brunob** [comment]
nice :)

**Pull request merged**
