### PR TITLE
Add OpenTopoMap layer

### PR DESCRIPTION
**Pull request by brunob**
New tiles from http://opentopomap.org with credits specified in http://opentopomap.org/about#verwendung

### CODE REVIEW

**Comment by brunob** [comment]
Maybe we can simplify credits by using `{attribution.OpenStreetMap}` ?

**Comment by jieter** [comment]
Nice layer, yes, attribution can be simplified.

**Comment by brunob** [comment]
done

**Comment by jieter** [comment]
:+1:

**Comment by brunob** [comment]
merged and published version 1.0.27

**Comment by brunob** [comment]
Maybe we should add this one to demo site ?

**Comment by brunob** [comment]
preview page at http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by jieter** [comment]
oh, right. 

For that, you'll only have to merge master in gh-pages...

**Comment by brunob** [comment]
done (y)

**Pull request merged**
