### PR TITLE
Add www.hikebikemap.org support

### PR DESCRIPTION
**Pull request by phenix-factory**

### CODE REVIEW

**Comment by jieter** [comment]
Hi, thanks for the pull. 

Can you fix the whitespace errors reported by Travis?

**Comment by phenix-factory** [comment]
I dont really understand what that travis thing want...

**Comment by jieter** [comment]
Mixing spaces and tabs?
```
leaflet-providers.js: line 455, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 455, col 15, Expected 'hikebike' to have an indentation at 9 instead at 15.
leaflet-providers.js: line 456, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 456, col 19, Expected 'url' to have an indentation at 13 instead at 19.
leaflet-providers.js: line 457, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 457, col 19, Expected 'options' to have an indentation at 13 instead at 19.
leaflet-providers.js: line 458, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 458, col 23, Expected 'attribution' to have an indentation at 17 instead at 23.
leaflet-providers.js: line 459, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 459, col 19, Expected '}' to have an indentation at 13 instead at 19.
leaflet-providers.js: line 460, col 1, Mixed spaces and tabs.
leaflet-providers.js: line 460, col 15, Expected '}' to have an indentation at 9 instead at 15.
```

**Comment by ximex** [comment]
I make a own pull request with fixed whitspaces
#122

**Comment by jieter** [comment]
Note that you could have updated this branch by force-pushing to it... (`git push origin patch-1 --force`, but )

**Comment by ximex** [comment]
this way was easier for me ;-)
I'm not a git pro

**Pull request closed without merging**
