### PR TITLE
HERE add traffic tiles to normal and hybrid

### PR DESCRIPTION
**Pull request by Daredzik**
+ normalDayTraffic 
add traffic to normal day tiles (in same layer)

+ hybridDayTraffic 
add traffic to hybrid day tiles (in same layer)

### CODE REVIEW

**Comment by Daredzik** [comment]
@brunob any chances to merge this in next few days ?

**Comment by brunob** [comment]
@jieter any thoughts ?

**Comment by jieter** [comment]
Looks good!

**Comment by agims7** [comment]
When will you publish these changes?

**Comment by Daredzik** [comment]
@brunob @jieter nice to merge this guys... but can you create release ?

**Comment by brunob** [comment]
No hurry...

**Comment by brunob** [comment]
just published to 1.9.0 now :)

**Comment by rjvarona** [comment]
lol i need this lol

**Comment by brunob** [comment]
@rjvarona ?

**Pull request merged**
