### PR TITLE
relative url for OSM FR tiles

### PR DESCRIPTION
**Pull request by brunob**
in order to allow diplaying them on https sites (thx to @erational & fdh.org)

### CODE REVIEW

**Comment by jieter** [comment]
Nice, merged

**Comment by brunob** [comment]
@jieter i'll take some time to check if over layers could benefit of this kind of modification

**Comment by jieter** [comment]
You know about the test script for that? 

https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/test-https-support.html

**Comment by brunob** [comment]
@jieter no i didn't, thx for pointing this one :)

**Pull request merged**
