### PR TITLE
Add Alidade Satellite style

### PR DESCRIPTION
**Pull request by ianthetechie**
Adds raster tile endpoint for Stadia Maps styles with satellite and aerial imagery.

### CODE REVIEW

**Comment by ianthetechie** [comment]
Change requests addressed.

**Review by brunob — APPROVED** [review]
Nice, should be squashed before merge :)

**Comment by ianthetechie** [comment]
Just to verify, would you like me to squash everything first? Or just a comment that you are using squash and merge (GitHub can do this automatically)?3/1/24 22:37, b_b ***@***.***> 작성:﻿
@brunob approved this pull request.

Nice, should be squashed before merge :)

**Comment by brunob** [comment]
This was just a reminder to myself, we will do the squash :)

**Review by jieter — APPROVED** [review]

**Comment by ianthetechie** [comment]
Done @brunob

**Pull request merged**
