### PR TITLE
Update leaflet-providers.js

### PR DESCRIPTION
**Pull request by slavino**
Fixed after discussion with maintainer/owner.

https://groups.google.com/d/msg/osm_sk/9JG7KGnC47c/hZhom2PtBQAJ

### CODE REVIEW

**Comment by brunob** [comment]
Thx, could you explain why you switched from jpeg tiles to png ones ?

**Comment by brunob** [comment]
@slavino bump...

**Comment by slavino** [comment]
oh, was based on feedback from their forum - just the URL wasn't valid as per SSL certificate and was causing issues. Whichever you like more should work flawlessly PNG or JPEG.

**Comment by brunob** [comment]
'k, since it's a base map and not an overlay, i think it's better to keep jpg tiles, could you modify your PR according to this please ?

**Comment by slavino** [comment]
Done it via GihHub web UI - hope there is no mess

**Comment by brunob** [comment]
@slavino thx :)

**Pull request merged**
