### PR TITLE
AMD support

### PR DESCRIPTION
**Pull request by dpix**
Would be awesome to have AMD support for this plugin. I've hacked in a fix but it would be cool to have proper amd support added, I.E. checking for existence of require etc

### CODE REVIEW

**Comment by jieter** [comment]
We can consider this if done properly. Please  update the pull and make sure travis is happy too.

**Comment by dpix** [comment]
Looks like your [last commit to master](https://github.com/leaflet-extras/leaflet-providers/commit/a39d5c36181680da2ef5255efa8402607ff9b9f0) has broken the tests as it is trying to use the same protocol to load leaflet from the cdn but the protocol in the tests is file://

**Comment by jieter** [comment]
Thanks for noticing, fixed in #165

**Comment by jieter** [comment]
@dpix looks good, let's merge!

**Comment by jieter** [comment]
released v1.1.0

**Comment by jieter** [comment]
Next time it would be nice if you can [squash the commits into one](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

**Pull request merged**
