### PR TITLE
remove OpenMapSurfer tile sources

### PR DESCRIPTION
**Pull request by tyrasd**
sadly, these layers will not be provided any longer :cry: 

//cc @Rungee

### CODE REVIEW

**Comment by brunob** [comment]
It works well from my side https://maps.heigit.org/openmapsurfer/tiles/hybrid/webmercator/7/66/44.png & https://maps.heigit.org/openmapsurfer/tiles/hybrid/webmercator/7/66/44.png

Could you explain your motivation and give us source info mentioning that it's closed ?

**Comment by tyrasd** [comment]
Well, these are just some of the tiles which are still in the tile cache. When you request other tiles, e.g. [https://maps.heigit.org/openmapsurfer/tiles/roads/webmercator/11/790/1057.png](https://maps.heigit.org/openmapsurfer/tiles/roads/webmercator/11/790/1057.png), you will get a 500 server error.

Some background: I work at the company which until now hosted the tiles (https://heigit.org). The short story is that our "MapSurfer.NET" rendering server recently crashed and now no one is still at the company knows hows how to set it up again from scratch. Also sadly the software behind it was never fully open source, and is therefore not something the company wants to continue to support. The decision was to completely show down the openmapsurfer tile service at HeiGIT quite soon. I just wanted to give you a timely heads-up.

**Comment by brunob** [comment]
Thx a lot for the info, sad news i was a early fan of these tile, we will remove them from this script asap.

**Comment by tyrasd** [comment]
Btw: here's a first announcement from some days ago: https://ask.openrouteservice.org/t/mapsurfer-endpoint-limitations/1442

**Comment by brunob** [comment]
@jieter could you watch why travis is blocking this PR please ?

**Comment by jieter** [comment]
No idea, but I'll merge anyway.

**Pull request merged**
