### PR TITLE
Layers NLS + bounds checking page.

### LINKED ISSUE #178: The Historical Map of Great Britain
National library of Scotland has this: http://nls.tileserver.com/

Very nice 1920 ~ 1940 maps

http://maps.nls.uk/projects/api/

### PR DESCRIPTION
**Pull request by jieter**
Adding some layers from the NLS goodness.

Still to be done:
- [x] Better names
- [x] Add bounds for Ireland
- [x] Make a test-bounds.html in preview to check them visually
- [x] Check bounds for other layers

Fixes #178

### CODE REVIEW

**Comment by brunob** [comment]
:+1:

**Comment by jieter** [comment]
Hmm, turns out that the Ireland layer assumes the grid origin is in the bottom left corner, so it needs something like [OpenLayers `{-y}`](http://openlayers.org/en/v3.8.2/apidoc/ol.source.XYZ.html) to work.

				'GSGS_Ireland': {
					 url: 'http://geo.nls.uk/maps/ireland/gsgs4136/{z}/{x}/{-y}.png',
					options: {
						minZoom: 5,
						maxZoom: 15,
						bounds: [[51.248163, -11.008300], [55.887635, -4.855957]]
					}
				}

So I'm removing it.

**Comment by jieter** [comment]
Hmm, sorry for adding so much unrelated stuff to this PR. But this is it for now.

**Comment by tomhughes** [comment]
@jieter the layers with the inverted Y axis just need the `tms: true` option setting on the layer.

I'm also interested to know where you found a lot of those tileserver URLs because they don't seem to match what the NLS portal uses?

**Comment by jieter** [comment]
@tomhughes 
Thanks for the `tms: true` tip, that works!

I think I got most of the urls by looking at the tiles these urls requested:
 - http://googlemapsmania.blogspot.nl/2015/09/the-rail-map-of-industrial-decline.html
 - http://maps.nls.uk/geo/explore/

IF (some) of these urls are not meant to be used as public API, please tell me or submit a pull request amending/removing them.

**Comment by tomhughes** [comment]
It's not that they're not meant to be used, it's just that when I look at http://maps.nls.uk/geo/explore/ I see it using http://geo.nls.uk/ for most of those layers. It looks like the answer is that you got them from the railway map, so I wonder where they got them from....

The tileserver.com URLs are nicer in that they have subdomains and https support, though some of them aren't as good for overlaying on other maps as they have blank tiles surrounding the map instead of transparent ones.

**Comment by tomhughes** [comment]
Incidentally the reason I was investigating was that I was trying to match them up with the layers I have at http://maps.compton.nu/ and add data for some of the extra layers I have (http://maps.compton.nu/js/map.js is the code I use currently).

**Pull request merged**
