### PR TITLE
Some stamen basemaps dont provide retina tiles

### PR DESCRIPTION
**Pull request by JLuc**
- See https://github.com/leaflet-extras/leaflet-providers/issues/283
- About stamen : https://github.com/stamen/maps.stamen.com/issues/56#issuecomment-398676347

### CODE REVIEW

**Comment by brunob** [comment]
Thx for the patch, let's discuss about it here https://github.com/leaflet-extras/leaflet-providers/pull/287#issuecomment-398860398 ;)

**Comment by brunob** [comment]
@jieter strange, the build seems to pass on travis-ci but we got a pending check here (?)

**Comment by jieter** [comment]
I restarted the build, let's see if that resolves it.

**Comment by brunob** [comment]
Nice, it works, i'm merging, updating the changelog and pushing a release.

**Pull request merged**
