### PR TITLE
change protocol to relative URL

### PR DESCRIPTION
**Pull request by ximex**
set all default to HTTP
please report all urls that have ssl support. i would push the changes
#89 
#116

### CODE REVIEW

**Comment by jieter** [comment]
Hmm, do we need the option `https:false` while most of the providers do not provide https? Would it make sense to have `https:true` for the layers we know support https?

**Comment by ximex** [comment]
thirst i think the count of providers they support https will grow.
it's not that easy to say. there are some cases we have to look at:

- Protocol of the page that executes the request
- Protocol support of the provider

So:
1) Page=HTTPS, Provider: both -> HTTPS (take the protocol from page)
2) Page=HTTPS, Provider: http -> HTTP (override the default)
3) Page=HTTP, Provider: http -> HTTP (take the protocol from page)
4) Page=HTTP, Provider: both -> this is the question! HTTPS override or default protocol from page?
The code of this pull request would choose the default protocol -> HTTP @4)

**Comment by jieter** [comment]
@calvinmetcalf @brunob thoughts?

**Comment by ximex** [comment]
Which bahavior do you want?

Page | Provider | Request
------ | ----------- | ----------
HTTPS | BOTH | HTTPS (Currently HTTP)
HTTPS | HTTP | HTTP
HTTP   | BOTH | HTTPS or HTTP? (Currently HTTP)
HTTP   | HTTP | HTTP

I don't think that there are providers that allow https only.

**Comment by jieter** [comment]
IF provider supports both, we should use the page protocol I think. I agree the provider list will grow, but we can invert the assumption: for now it makes more sense to me to assume the provider does not support https. There is no need to repeat `HTTPS: false` for every variant if it is set in the topmost `options` map.
Another approach might be: leave the protocol part out of the url for those providers known to support both and just leave it there for all others.

When applying this update, we should fix the preview page code copy control too.

**Comment by ximex** [comment]
One problem i found with `//www.example.org/` urls is, if you open your html local, the protocol won't be http or https, it would be: `file://`

You mean we set `HTTPS: false` in the gobal `options` and only set an `HTTPS: true` property if the providers supports it.

What do you mean with the last sentence?

**Comment by jieter** [comment]
We could add something like a `force_http` option... 

Your second poind: For example if HERE does not support https, you can (in your approach) set https: false in its topmost options map and omit it in every options map for its variants.

**Comment by ximex** [comment]
strange merge conflict...
`url: 'http://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.jpeg',`
to
`url: '//maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.jpeg',`

do you mean this way? and then we have to set the `force_https` flags

**Comment by jieter** [comment]
Or default to http if window.location.protocol == 'file:'

Tried to detect https support for providers: not bullet proof, but it's a start: https://gist.github.com/jieter/6ccf4f215e514355f501

**Comment by jieter** [comment]
no, not this way.

For providers supporting both, remove protocol, use auto-detect if `window.location.protocol != 'file:'` and leave the rest unchanged.

**Comment by ximex** [comment]
that way?

**Comment by jieter** [comment]
Sorry, I'm not that clear today. 
Apart from the typo in your last commit (`fore_http`), you remove the protocol from every single url. My point is that you shouldn't touch provider urls for which you know https is not supported.

Then IF you know https is supported, do the force_http/`window.location === 'file' check.

**Comment by jieter** [comment]
@ximex #135 is like my take at it.

**Pull request closed without merging**
