### PR TITLE
Add CartoDB labels-only styles

### PR DESCRIPTION
**Pull request by almccon**
see http://blog.cartodb.com/let-your-labels-shine/

### CODE REVIEW

**Comment by brunob** [comment]
Thx, seems ok to merge, think the travis warning is wrong.

**Comment by ximex** [comment]
Maybe this is of the change from travis to docker containers: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by jieter** [comment]
build fixed, merging.

**Comment by jieter** [comment]
Thanks!

**Pull request merged**
