### PR TITLE
TopPlusOpen and BaseMapDe added

### PR DESCRIPTION
**Pull request by stell**

### CODE REVIEW

**Comment by brunob** [comment]
Since these one are on the same domain `sgx.geodatenzentrum.de` maybe it would be better to group them in one provider ? @jieter ?

**Comment by jieter** [comment]
If the current names are more recognisable, I'd say it can also be kept as it is now.

**Comment by brunob** [comment]
Ready to merge :)

**Comment by brunob** [comment]
Thx @stell :)

**Pull request merged**
