### PR TITLE
Added new variants to HERE and made the URL more dynamic.

### PR DESCRIPTION
**Pull request by andreaswc**
In my project i need to:

* Split HERE into different layers to be able to toggle trafficflow on/off.
* Select language for the label layer.
* Prioritize each layer so trafficflow does not cover labels.

Thought others might want to do the same thing, in any case the URL for HERE is now more dynamic and I've added a couple of variants to get layers of the map rather than an entire map.

### CODE REVIEW

**Comment by jieter** [comment]
The `size` option is not used by any of the variants, it's just included for flexibility right?
I'm not sure how far we should go with things like that. Thoughts @brunob ? 

What do we want to strive for with leaflet-providers? Just a list of working free tile layers? Or do we want to support every provider as much as possible?

**Comment by jieter** [comment]
Also: this makes the list of variants for HERE huge. I think we need to do something to make it less prominent the preview list.

**Comment by andreaswc** [comment]
Yes, the size is only for flexibility.

**Comment by jieter** [comment]
Why are you closing? We're just not that fast in deciding what to do...

**Comment by brunob** [comment]
> I think we need to do something to make it less prominent the preview list.

I agree, we already have 19 layers for here on the preview page...

@jieter what do you think of basicMap option for OpsenStreetMap, is it useful ?

> I'm not sure how far we should go with things like that. Thoughts @brunob ? What do we want to strive for with leaflet-providers? Just a list of working free tile layers? Or do we want to support every provider as much as possible? 

Not sure too, KISS is nice, but it seems useful for @andreaswc so it may be the same for other users.

**Comment by andreaswc** [comment]
I removed basicMap for OpenStreetMap as it was only experimental. What I do want you to consider is adding the basicMap, tafficFlow and mapLabels for HERE and also the additional options.

**Comment by jieter** [comment]
OK, let's just add this. 

Currently, the merge has conflicts. Please revert the changes to `package.json` and `bower.json` (They'll be updated automatically once I release) and squash the commits into one.

**Comment by andreaswc** [comment]
Alright, they have been reverted.

**Comment by jieter** [comment]
Hmm, still conflicts. Can you rebase and squash the commits into one?

**Comment by andreaswc** [comment]
does it work now? Just added the changes for HERE to the current master.

**Comment by jieter** [comment]
hmm, not really, as you can see at the bottom of the PR page. I also asked to squash all your commits into one. That commit should only touch the HERE part of `leaflet-providers.js`, and no other files.

This might help: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by andreaswc** [comment]
There we go!

**Comment by jieter** [comment]
Hmm, yeah, this is almost what I wanted and good enough for now, thanks. To avoid the `Merge branch 'master' into master`-commit, you should have used `git push --force`

**Comment by andreaswc** [comment]
I did use -f, then I went on github to check if it worked (which it did). However, it asked me to "update" with the changes from master so that's probably where it went wrong. I can redo the procedure without updating if you want.

**Comment by jieter** [comment]
Yes, this is it! Thanks.

**Pull request merged**
