### PR TITLE
Add travis nodejs versions

### PR DESCRIPTION
**Pull request by ximex**
test with new stable nodejs 0.12 and latest iojs

### CODE REVIEW

**Comment by jieter** [comment]
The only thing we really do is run `eslint`, do we need more node versions for that?

**Comment by ximex** [comment]
my device is: did it cost something? than why not? maybe there is more something comming in the future ;-)

**Comment by jieter** [comment]
Free CI at Travis runs on real hardware costing real money. 

And it has to run 3 times before travis can report success (taking more time). Not sure if that will be 3 different instances or if node will be swapped in the same instance.

**Comment by ximex** [comment]
i think this are 3 instances. But travis runs up to 3 instances parallel.
So not more time but little more costs for travis.
it's your decision ;-) i only want to help to improve software =)

**Comment by jieter** [comment]
We'll add this if a more sophisticated test suite is created.

**Pull request closed without merging**
