### PR TITLE
Added OneMap (Singapore)

### PR DESCRIPTION
**Pull request by kyroskoh**

### CODE REVIEW

**Comment by jieter** [comment]
@kartenkarsten thanks for the pull. For reference, can you provide a link to this providers TOS in a comment here?

**Comment by jieter** [comment]
@kyroskoh thanks for the PR, I merged it and did the requested changes, see commit 9732ecbd6cf74dcdfde2005d205cab64e9044901

**Comment by jieter** [comment]
released [1.4.0](https://www.npmjs.com/package/leaflet-providers/v/1.4.0)

**Comment by brunob** [comment]
:+1:  @jieter :)

**Comment by kyroskoh** [comment]
@brunob The attribution logo is needed as it is part of the Trademark of OneMap SG.

**Comment by brunob** [comment]
@kyroskoh like @jieter said : 

> can you provide a link to this providers TOS in a comment here?

**Comment by brunob** [comment]
I've read https://www.onemap.sg/legal/termsofuse.html and could not find any mention to a way of crediting original website. Maybe the best options would be to contact them to ask if the image have to be present in credits.

**Comment by kyroskoh** [comment]
@brunob I was being told by them to use the same attribution that they have declared. Do you want to contact them to ask about it?

**Comment by brunob** [comment]
@kyroskoh 'k let's go for the image in credits :)

**Pull request merged**
