### PR TITLE
Add a test to prevent accidental removal of placeholders in urls

### PR DESCRIPTION
**Pull request by jieter**
This could have prevented the toposm-relief part of #184.

I'll try to refactor it a bit later.

### CODE REVIEW

**Comment by jieter** [comment]
This is more like it. @brunob .

Are you still alive @calvinmetcalf ;)?

**Comment by brunob** [comment]
Seems ok to me, but i don't see anything about ext var in the code, maybe it's normal ?

**Comment by jieter** [comment]
No, no `{ext}` var, it checks if the keys in the options map are either valid L.TileLayer options or have a placeholder in the url. In the case of this `{ext}` missing from the url, the test fails with this message:

```
 11) leaflet-providers Each layer Stamen.TopOSMFeatures should have valid options:
     AssertionError: expected 'http://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}.png' to include '{ext}'
```

**Comment by brunob** [comment]
Great :)

**Pull request merged**
