### PR TITLE
Final https touches

### LINKED ISSUE #116: SSL support for MapQuest OSM
I know that MapQuest OSM supports SSL, but the provider URL seems to be hardcoded to 'http', this is triggering mixed-content warnings on my site (which is SSL-only).

### PR DESCRIPTION
**Pull request by jieter**
- Add a note about https support for MapQuest in code (sort of fixes #116).
- Document protocol relativity in README.md.
- Remove list of ESRI variants + let preview link stand out a little more.

### CODE REVIEW

**Comment by ximex** [comment]
:+1:

**Comment by ximex** [comment]
you could use the `https` url in all `http://leaflet-extras.github.io/leaflet-providers/` links

**Comment by jieter** [comment]
Thanks for the feedback, just pushed some clarifications and updated the HERE url.

**Comment by brunob** [comment]
:+1:

**Comment by jieter** [comment]
released v1.0.26

**Pull request merged**
