### PR TITLE
docs(changelog): update changelog for v2.0.0

### PR DESCRIPTION
**Pull request by brunob**
and keep only one entry for #522

### CODE REVIEW

**Review by jieter — APPROVED** [review]
👍

**Comment by brunob** [comment]
Now we juste have to : merge this, update release date in changelog and push a new release to npm.

**Comment by jieter** [comment]
I'll do the remaining two steps.

**Comment by jieter** [comment]
Released v2.0.0: https://www.npmjs.com/package/leaflet-providers/v/2.0.0

**Comment by jieter** [comment]
It was about time:

Screenshot 2023-08-28 at 20 15 58

**Comment by brunob** [comment]
We should release more often :p Maybe we can plan to release every two or three months.

**Comment by jieter** [comment]
Yes it might be helpful if we can automate it a bit more.

But before that, we should find an alternative for mocha-chrome, which stopped working (I removed the tests from CI for now).

**Comment by brunob** [comment]
> Yes it might be helpful if we can automate it a bit more.

Changelog can be automated but in don't think it's a good idea, i can spare time on this. So we "just" have to put a reminder or ping ourselves every X months (if we have time for this).

> But to  before that, we should find an alternative for mocha-chrome, which stopped working (I removed the tests from CI for now).

For sure :\

**Pull request merged**
