### PR TITLE
Add www.hikebikemap.org support

### PR DESCRIPTION
**Pull request by ximex**

### CODE REVIEW

**Comment by jieter** [comment]
Looks good, thanks1

**Comment by jieter** [comment]
released 1.0.14 and updated at github pages.

**Comment by ximex** [comment]
How is it possible to push another commit if i add this commit after the merge of the pull request?
https://github.com/ximex/leaflet-providers/commit/d4e0b8924042c0ff5b7f573dd36ff54116b1eeb0

**Comment by jieter** [comment]
Only before I merged it, of course.

**Pull request merged**
