### PR TITLE
RIP acetate tiles

### PR DESCRIPTION
**Pull request by brunob**
Acetate tiles no more available :( cf https://twitter.com/ajturner/status/675853179909705728

### CODE REVIEW

**Comment by jieter** [comment]
Hmm, that's a pity. Looks good, merging...

**Comment by brunob** [comment]
Yes, a pity, i feel a bit nostalgic when i remember my first web map using this tiles... Thx for the merge.

**Comment by jieter** [comment]
I'll have to update [layerscontrol-minimap](https://github.com/jieter/Leaflet.layerscontrol-minimap) too, and the leaflet-provider preview too...

**Comment by jieter** [comment]
released 1.1.7

**Pull request merged**
